language: android

android:
    components:
        - platform-tools
        - tools
        - android-24
        - build-tools-24.0.1
        - extra-google-google_play_services

script:
  - ./gradlew build connectedCheck
  
notifications:
  email: false
