language: android

android:
    components:
        - platform-tools
        - tools
        - android-26
        - build-tools-26.0.0
        - extra-google-m2repository
        - extra-android-m2repository
        - extra-android-support
        - extra-google-google_play_services

jdk:
  - oraclejdk8

script:
  - ./gradlew build connectedCheck
  
notifications:
  email: false
