language: android

android:
    components:
        - platform-tools
        - tools
        - android-25
        - build-tools-25.0.3
        - extra-google-m2repository
        - extra-android-m2repository
        - extra-google-google_play_services

jdk:
  - oraclejdk8

script:
  - ./gradlew build connectedCheck
  
notifications:
  email: false
